import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import hre from "hardhat";

const TOKEN_NAME = process.env.NIX_TOKEN_NAME ?? "Nix Token";
const TOKEN_SYMBOL = process.env.NIX_TOKEN_SYMBOL ?? "NIX";
const BIDDING_SECONDS = Number(process.env.LAUNCH_BIDDING_SECONDS ?? 7 * 24 * 60 * 60);

type DeploymentRecord = {
  chainId: number;
  network: string;
  deployer: string;
  NixToken: string;
  IntentRegistry: string;
  NixPool: string;
  NixLaunch: string;
};

function envUint(name: string, fallback: bigint): bigint {
  const raw = process.env[name];
  if (!raw) return fallback;
  const value = BigInt(raw);
  if (value <= 0n || value > 18446744073709551615n) {
    throw new Error(`${name} must be a positive uint64.`);
  }
  return value;
}

function requireAddress(value: string, label: string): string {
  if (!hre.ethers.isAddress(value)) {
    throw new Error(`${label} is not an address: ${value}`);
  }
  return hre.ethers.getAddress(value);
}

function loadDeployments(jsonPath: string): Record<string, DeploymentRecord> {
  if (!existsSync(jsonPath)) return {};
  const parsed: unknown = JSON.parse(readFileSync(jsonPath, "utf8"));
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`${jsonPath} must be an object keyed by chain id.`);
  }
  return parsed as Record<string, DeploymentRecord>;
}

function renderContracts(
  abis: Record<string, unknown>,
  deployments: Record<string, DeploymentRecord>,
): string {
  return `// Generated by scripts/deploy.ts. Do not edit by hand.

export const abis = ${JSON.stringify(abis, null, 2)} as const;

export const deployments = ${JSON.stringify(deployments, null, 2)} as const;
`;
}

async function main() {
  const networkName = hre.network.name;
  const isLocal = networkName === "hardhat" || networkName === "localhost";
  if (!isLocal && !process.env.PRIVATE_KEY) {
    throw new Error("Set PRIVATE_KEY in .env before deploying to a public network.");
  }

  const [deployer] = await hre.ethers.getSigners();
  if (!deployer) {
    throw new Error("No deployer account is configured for this network.");
  }

  const chainId = Number(hre.network.config.chainId);
  if (!Number.isInteger(chainId)) {
    throw new Error(`Network ${networkName} has no chain id.`);
  }
  if (!Number.isInteger(BIDDING_SECONDS) || BIDDING_SECONDS <= 0) {
    throw new Error("LAUNCH_BIDDING_SECONDS must be a positive number of seconds.");
  }

  const token = await hre.ethers.deployContract("NixToken", [
    TOKEN_NAME,
    TOKEN_SYMBOL,
    deployer.address,
  ]);
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();

  const registry = await hre.ethers.deployContract("IntentRegistry", [deployer.address]);
  await registry.waitForDeployment();

  const pool = await hre.ethers.deployContract("NixPool", [tokenAddress]);
  await pool.waitForDeployment();

  const latest = await hre.ethers.provider.getBlock("latest");
  if (!latest) {
    throw new Error("Could not read the latest block for the launch schedule.");
  }
  // NixLaunch uses one NixToken as both payment and sale token unless an address is set.
  const paymentToken = requireAddress(
    process.env.PAYMENT_TOKEN_ADDRESS ?? tokenAddress,
    "PAYMENT_TOKEN_ADDRESS",
  );
  const saleToken = requireAddress(
    process.env.SALE_TOKEN_ADDRESS ?? tokenAddress,
    "SALE_TOKEN_ADDRESS",
  );
  const launch = await hre.ethers.deployContract("NixLaunch", [
    paymentToken,
    saleToken,
    envUint("LAUNCH_TOKENS_FOR_SALE", 1_000_000n),
    envUint("LAUNCH_BASE_PRICE", 2n),
    envUint("LAUNCH_CURVE_STEP", 1_000n),
    BigInt(latest.timestamp) + BigInt(BIDDING_SECONDS),
  ]);
  await launch.waitForDeployment();

  const record: DeploymentRecord = {
    chainId,
    network: networkName,
    deployer: deployer.address,
    NixToken: tokenAddress,
    IntentRegistry: await registry.getAddress(),
    NixPool: await pool.getAddress(),
    NixLaunch: await launch.getAddress(),
  };

  const configDir = path.join(process.cwd(), "frontend", "config");
  const jsonPath = path.join(configDir, "deployments.json");
  const tsPath = path.join(configDir, "contracts.ts");
  mkdirSync(configDir, { recursive: true });

  const deployments = loadDeployments(jsonPath);
  deployments[String(chainId)] = record;
  const ordered = Object.fromEntries(
    Object.entries(deployments).sort(([left], [right]) => Number(left) - Number(right)),
  );

  const names = ["NixToken", "IntentRegistry", "NixPool", "NixLaunch"] as const;
  const abis: Record<(typeof names)[number], unknown> = {
    NixToken: [],
    IntentRegistry: [],
    NixPool: [],
    NixLaunch: [],
  };
  for (const name of names) {
    abis[name] = (await hre.artifacts.readArtifact(name)).abi;
  }

  writeFileSync(jsonPath, `${JSON.stringify(ordered, null, 2)}\n`);
  writeFileSync(tsPath, renderContracts(abis, ordered));

  console.log(`Deployed on ${networkName} (${chainId})`);
  for (const name of names) {
    console.log(`${name}: ${record[name]}`);
  }
  console.log(`Wrote ${path.relative(process.cwd(), tsPath)}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
