import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import hre from "hardhat";

const TOKEN_NAME = process.env.NIX_TOKEN_NAME ?? "Nix Token";
const TOKEN_SYMBOL = process.env.NIX_TOKEN_SYMBOL ?? "NIX";
const BIDDING_SECONDS = Number(process.env.LAUNCH_BIDDING_SECONDS ?? 7 * 24 * 60 * 60);

const INITIAL_SUPPLY = 1_000_000_000n * 10n ** 18n;

type DeploymentRecord = {
  chainId: number;
  network: string;
  deployer: string;
  NixToken: string;
  IntentRegistry: string;
  NixPool: string;
  NixLaunch: string;
  NixLaunchpad: string;
};

function envUint(name: string, fallback: bigint): bigint {
  const raw = process.env[name];
  if (!raw) return fallback;
  const value = BigInt(raw);
  if (value <= 0n || value > 18446744073709551615n) {
    throw new Error(`${name} must be a positive uint64.`);
  }
  return value;
}

function requireAddress(value: string, label: string): string {
  if (!hre.ethers.isAddress(value)) {
    throw new Error(`${label} is not an address: ${value}`);
  }
  return hre.ethers.getAddress(value);
}

function loadDeployments(jsonPath: string): Record<string, DeploymentRecord> {
  if (!existsSync(jsonPath)) return {};
  const parsed: unknown = JSON.parse(readFileSync(jsonPath, "utf8"));
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`${jsonPath} must be an object keyed by chain id.`);
  }
  return parsed as Record<string, DeploymentRecord>;
}

function renderContracts(
  abis: Record<string, unknown>,
  deployments: Record<string, DeploymentRecord>,
): string {
  return `// Generated by scripts/deploy.ts. Do not edit by hand.

export const abis = ${JSON.stringify(abis, null, 2)} as const;

export const deployments = ${JSON.stringify(deployments, null, 2)} as const;
`;
}

const L2_CHAIN_IDS = new Set([84532, 421614]);

let nonce = 0;
let confirmations = 1;
let deployer!: Awaited<ReturnType<typeof hre.ethers.getSigners>>[number];

type DeployOverrides = {
  nonce: number;
  gasLimit?: bigint;
  maxFeePerGas?: bigint;
  maxPriorityFeePerGas?: bigint;
};

async function main() {
  const networkName = hre.network.name;
  const isLocal = networkName === "hardhat" || networkName === "localhost";
  if (!isLocal && !process.env.PRIVATE_KEY) {
    throw new Error("Set PRIVATE_KEY in .env before deploying to a public network.");
  }

  const [signer] = await hre.ethers.getSigners();
  if (!signer) {
    throw new Error("No deployer account is configured for this network.");
  }
  deployer = signer;

  const chainId = Number(hre.network.config.chainId);
  if (!Number.isInteger(chainId)) {
    throw new Error(`Network ${networkName} has no chain id.`);
  }
  if (!Number.isInteger(BIDDING_SECONDS) || BIDDING_SECONDS <= 0) {
    throw new Error("LAUNCH_BIDDING_SECONDS must be a positive number of seconds.");
  }

  // Base and Arbitrum need two confirmations before eth_call sees the new storage.
  // Hardhat mines one block per transaction, so it keeps a single confirmation.
  confirmations = L2_CHAIN_IDS.has(chainId) ? 2 : 1;
  nonce = await settledNonce(deployer.address);
  console.log(`Deploying from ${deployer.address} at nonce ${nonce} with ${confirmations} confirmation(s).`);

  if (process.env.REPLACE_SWAP === "1") {
    await replaceSwap(chainId, networkName);
    return;
  }

  if (process.env.REPLACE_LAUNCHPAD === "1") {
    await replaceLaunchpad(chainId, networkName);
    return;
  }

  const token = await deployFresh("NixToken", [TOKEN_NAME, TOKEN_SYMBOL, deployer.address]);
  const tokenAddress = await token.getAddress();
  const expectedSupply = await token.INITIAL_SUPPLY();
  if (expectedSupply !== INITIAL_SUPPLY) {
    throw new Error(`NixToken.INITIAL_SUPPLY is ${expectedSupply}, expected ${INITIAL_SUPPLY}.`);
  }
  const mintReceipt = await send(token.mint(deployer.address, INITIAL_SUPPLY, await overrides()));
  const supply = await supplyAfterMint(token, mintReceipt.blockNumber, expectedSupply);
  console.log(`Mint confirmed in block ${mintReceipt.blockNumber}. totalSupply=${supply}`);

  const registry = await deployFresh("IntentRegistry", [deployer.address]);
  await send(registry.setSolver(deployer.address, true, await overrides()));

  const pool = await deployFresh("NixPool", [tokenAddress]);

  const latest = await hre.ethers.provider.getBlock("latest");
  if (!latest) {
    throw new Error("Could not read the latest block for the launch schedule.");
  }
  // NixLaunch uses one NixToken as both payment and sale token unless an address is set.
  const paymentToken = requireAddress(
    process.env.PAYMENT_TOKEN_ADDRESS ?? tokenAddress,
    "PAYMENT_TOKEN_ADDRESS",
  );
  const saleToken = requireAddress(
    process.env.SALE_TOKEN_ADDRESS ?? tokenAddress,
    "SALE_TOKEN_ADDRESS",
  );
  const launch = await deployFresh("NixLaunch", [
    paymentToken,
    saleToken,
    envUint("LAUNCH_TOKENS_FOR_SALE", 1_000_000n),
    envUint("LAUNCH_BASE_PRICE", 2n),
    envUint("LAUNCH_CURVE_STEP", 1_000n),
    BigInt(latest.timestamp) + BigInt(BIDDING_SECONDS),
  ]);

  const launchpad = await deployFresh("NixLaunchpad", [tokenAddress]);
  await fundLaunchSeed(token, launchpad);

  const record: DeploymentRecord = {
    chainId,
    network: networkName,
    deployer: deployer.address,
    NixToken: tokenAddress,
    IntentRegistry: await registry.getAddress(),
    NixPool: await pool.getAddress(),
    NixLaunch: await launch.getAddress(),
    NixLaunchpad: await launchpad.getAddress(),
  };

  await writeFrontendConfig({ [String(chainId)]: record });

  console.log(`Deployed on ${networkName} (${chainId})`);
  console.log(`NIX total supply: ${supply} minted to ${deployer.address}`);
  console.log("Faucet: claimFaucet() sends 500 NIX from the deployer, once per address per day.");
  console.log(`Solver whitelisted: ${deployer.address}`);
  for (const name of ["NixToken", "IntentRegistry", "NixPool", "NixLaunch", "NixLaunchpad"] as const) {
    console.log(`${name}: ${record[name]}`);
  }
}

type SeedToken = {
  balanceOf: (account: string) => Promise<bigint>;
  approve: (
    spender: string,
    amount: bigint,
    txOverrides: DeployOverrides,
  ) => Promise<{
    wait: (confirms: number) => Promise<{ status: number | null; blockNumber: number; hash: string } | null>;
    hash: string;
  }>;
};

type SeedLaunchpad = {
  getAddress: () => Promise<string>;
  SEED_NIX: () => Promise<bigint>;
  fundSeed: (
    amount: bigint,
    txOverrides: DeployOverrides,
  ) => Promise<{
    wait: (confirms: number) => Promise<{ status: number | null; blockNumber: number; hash: string } | null>;
    hash: string;
  }>;
};

async function fundLaunchSeed(token: SeedToken, launchpad: SeedLaunchpad) {
  const launchpadAddress = await launchpad.getAddress();
  const seed = await launchpad.SEED_NIX();
  const balance = await token.balanceOf(deployer.address);
  const covered = balance / seed;
  if (covered < 1n) {
    throw new Error(`Deployer NIX balance ${balance} is below one seed of ${seed}.`);
  }
  const launches = covered > 100n ? 100n : covered;
  const budget = seed * launches;
  await send(token.approve(launchpadAddress, budget, await overrides()));
  await send(launchpad.fundSeed(budget, await overrides()));
  console.log(`Funded ${launchpadAddress} with ${budget} NIX (${launches} opening pools).`);
}

async function replaceSwap(chainId: number, networkName: string) {
  const jsonPath = path.join(process.cwd(), "frontend", "config", "deployments.json");
  const deployments = loadDeployments(jsonPath);
  const existing = deployments[String(chainId)];
  if (!existing?.NixToken) {
    throw new Error(`No NixToken is saved for chain ${chainId}.`);
  }
  const token = await hre.ethers.getContractAt("NixToken", existing.NixToken, deployer);
  const registry = await deployFresh("IntentRegistry", [deployer.address]);
  await send(registry.setSolver(deployer.address, true, await overrides()));
  const launchpad = await deployFresh("NixLaunchpad", [existing.NixToken]);
  await fundLaunchSeed(token, launchpad);
  existing.IntentRegistry = await registry.getAddress();
  existing.NixLaunchpad = await launchpad.getAddress();
  existing.network = networkName;
  existing.deployer = deployer.address;
  await writeFrontendConfig({ [String(chainId)]: existing });
  console.log(`Replaced IntentRegistry on ${networkName}: ${existing.IntentRegistry}`);
  console.log(`Replaced NixLaunchpad on ${networkName}: ${existing.NixLaunchpad}`);
  console.log(`Solver whitelisted: ${deployer.address}`);
}

async function replaceLaunchpad(chainId: number, networkName: string) {
  const jsonPath = path.join(process.cwd(), "frontend", "config", "deployments.json");
  const deployments = loadDeployments(jsonPath);
  const existing = deployments[String(chainId)];
  if (!existing?.NixToken) {
    throw new Error(`No NixToken is saved for chain ${chainId}.`);
  }
  const token = await hre.ethers.getContractAt("NixToken", existing.NixToken, deployer);
  const launchpad = await deployFresh("NixLaunchpad", [existing.NixToken]);
  await fundLaunchSeed(token, launchpad);
  existing.NixLaunchpad = await launchpad.getAddress();
  existing.network = networkName;
  existing.deployer = deployer.address;
  await writeFrontendConfig({ [String(chainId)]: existing });
  console.log(`Replaced NixLaunchpad on ${networkName}: ${existing.NixLaunchpad}`);
}

async function writeFrontendConfig(updates: Record<string, DeploymentRecord>) {
  const configDir = path.join(process.cwd(), "frontend", "config");
  const jsonPath = path.join(configDir, "deployments.json");
  const tsPath = path.join(configDir, "contracts.ts");
  mkdirSync(configDir, { recursive: true });

  const deployments = loadDeployments(jsonPath);
  Object.assign(deployments, updates);
  const ordered = Object.fromEntries(
    Object.entries(deployments).sort(([left], [right]) => Number(left) - Number(right)),
  );

  const names = ["NixToken", "IntentRegistry", "NixPool", "NixLaunch", "NixLaunchpad", "NixPair", "LaunchToken"] as const;
  const abis: Record<(typeof names)[number], unknown> = {
    NixToken: [],
    IntentRegistry: [],
    NixPool: [],
    NixLaunch: [],
    NixLaunchpad: [],
    NixPair: [],
    LaunchToken: [],
  };
  for (const name of names) {
    abis[name] = (await hre.artifacts.readArtifact(name)).abi;
  }

  writeFileSync(jsonPath, `${JSON.stringify(ordered, null, 2)}\n`);
  writeFileSync(tsPath, renderContracts(abis, ordered));
  console.log(`Wrote ${path.relative(process.cwd(), tsPath)}`);
}

async function settledNonce(account: string) {
  const provider = hre.ethers.provider;
  let latest = await provider.getTransactionCount(account, "latest");
  let pending = await provider.getTransactionCount(account, "pending");
  const started = Date.now();
  while (pending > latest && Date.now() - started < 90_000) {
    console.log(`Waiting for in-flight transactions (latest nonce ${latest}, pending nonce ${pending}).`);
    await delay(3_000);
    latest = await provider.getTransactionCount(account, "latest");
    pending = await provider.getTransactionCount(account, "pending");
  }
  if (pending !== latest) {
    throw new Error(
      `Deployer ${account} still has in-flight transactions (latest nonce ${latest}, pending nonce ${pending}). Wait for them to confirm, then redeploy.`,
    );
  }
  return latest;
}

async function feeFields() {
  if (hre.network.name === "hardhat" || hre.network.name === "localhost") return {};
  const fee = await hre.ethers.provider.getFeeData();
  const fields: { maxFeePerGas?: bigint; maxPriorityFeePerGas?: bigint } = {};
  if (fee.maxPriorityFeePerGas && fee.maxPriorityFeePerGas > 0n) {
    fields.maxPriorityFeePerGas = fee.maxPriorityFeePerGas * 2n;
  }
  if (fee.maxFeePerGas && fee.maxFeePerGas > 0n) {
    fields.maxFeePerGas = fee.maxFeePerGas * 2n;
  }
  if (
    fields.maxFeePerGas !== undefined &&
    fields.maxPriorityFeePerGas !== undefined &&
    fields.maxPriorityFeePerGas > fields.maxFeePerGas
  ) {
    fields.maxFeePerGas = fields.maxPriorityFeePerGas;
  }
  return fields;
}

async function overrides(): Promise<DeployOverrides> {
  const next: DeployOverrides = { nonce, ...(await feeFields()) };
  nonce += 1;
  return next;
}

async function deployFresh(name: string, args: unknown[]) {
  const factory = await hre.ethers.getContractFactory(name, deployer);
  const txOverrides = await overrides();
  const unsigned = await factory.getDeployTransaction(...(args as []));
  try {
    const estimated = await deployer.estimateGas({ ...unsigned, nonce: txOverrides.nonce });
    txOverrides.gasLimit = (estimated * 130n) / 100n + 100_000n;
  } catch (error) {
    const detail = error instanceof Error ? error.message.split("\n")[0] : String(error);
    console.warn(`Gas estimation reverted for ${name}. Sending with an explicit gas limit. ${detail}`);
    txOverrides.gasLimit = 30_000_000n;
  }

  const deployed = await factory.deploy(...(args as []), txOverrides);
  const sent = deployed.deploymentTransaction();
  if (!sent) throw new Error(`${name} did not produce a deployment transaction.`);
  const receipt = await sent.wait(confirmations);
  if (!receipt || receipt.status !== 1 || !receipt.contractAddress) {
    throw new Error(`${name} deployment ${sent.hash} was not confirmed.`);
  }

  // Read code at the receipt block. Do not trust a cached address from an earlier deploy.
  const code = await hre.ethers.provider.getCode(receipt.contractAddress, receipt.blockNumber);
  if (!code || code === "0x") {
    throw new Error(`${name} has no code at ${receipt.contractAddress} in block ${receipt.blockNumber}.`);
  }
  console.log(`${name} deployed at ${receipt.contractAddress} (nonce ${txOverrides.nonce}, tx ${sent.hash}).`);
  return hre.ethers.getContractAt(name, receipt.contractAddress, deployer);
}

async function send(pending: Promise<{ wait: (confirms: number) => Promise<{ status: number | null; blockNumber: number; hash: string } | null>; hash: string }>) {
  const tx = await pending;
  const receipt = await tx.wait(confirmations);
  if (!receipt || receipt.status !== 1) {
    throw new Error(`Transaction ${tx.hash} did not confirm.`);
  }
  return receipt;
}

async function supplyAfterMint(
  token: { totalSupply: (opts?: { blockTag: number }) => Promise<bigint> },
  blockNumber: number,
  expected: bigint,
) {
  let seen = 0n;
  for (let attempt = 0; attempt < 6; attempt += 1) {
    try {
      seen = await token.totalSupply({ blockTag: blockNumber });
    } catch {
      seen = await token.totalSupply();
    }
    if (seen === expected) return seen;
    console.log(`totalSupply is ${seen} at block ${blockNumber}; waiting for the L2 state (${attempt + 1}/6).`);
    await delay(2_000);
  }
  throw new Error(`NIX total supply is ${seen}, expected exactly ${expected}.`);
}

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
