import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import hre from "hardhat";

export const FRONTEND_CONTRACTS = [
  "NixToken",
  "IntentRegistry",
  "NixPool",
  "NixLaunch",
  "NixLaunchpad",
  "NixPair",
  "LaunchToken",
  "NixBridge",
] as const;

export type DeploymentRecord = {
  chainId: number;
  network: string;
  deployer: string;
  NixToken: string;
  IntentRegistry: string;
  NixPool: string;
  NixLaunch: string;
  NixLaunchpad: string;
  NixBridge?: string;
};

export function loadDeployments(jsonPath: string): Record<string, DeploymentRecord> {
  if (!existsSync(jsonPath)) return {};
  const parsed: unknown = JSON.parse(readFileSync(jsonPath, "utf8"));
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`${jsonPath} must be an object keyed by chain id.`);
  }
  return parsed as Record<string, DeploymentRecord>;
}

function renderContracts(abis: Record<string, unknown>, deployments: Record<string, DeploymentRecord>) {
  return `// Generated by scripts/deploy.ts. Do not edit by hand.

export const abis = ${JSON.stringify(abis, null, 2)} as const;

export const deployments = ${JSON.stringify(deployments, null, 2)} as const;
`;
}

export async function writeFrontendConfig(updates: Record<string, DeploymentRecord>) {
  const configDir = path.join(process.cwd(), "frontend", "config");
  const jsonPath = path.join(configDir, "deployments.json");
  const tsPath = path.join(configDir, "contracts.ts");
  mkdirSync(configDir, { recursive: true });

  const deployments = loadDeployments(jsonPath);
  for (const [chainId, update] of Object.entries(updates)) {
    const previous = deployments[chainId];
    const merged: DeploymentRecord = { ...previous, ...update };
    if (
      previous?.NixToken &&
      update.NixToken &&
      previous.NixToken.toLowerCase() !== update.NixToken.toLowerCase()
    ) {
      delete merged.NixBridge;
    }
    deployments[chainId] = merged;
  }
  const ordered = Object.fromEntries(
    Object.entries(deployments).sort(([left], [right]) => Number(left) - Number(right)),
  );

  const abis: Record<string, unknown> = {};
  for (const name of FRONTEND_CONTRACTS) {
    abis[name] = (await hre.artifacts.readArtifact(name)).abi;
  }

  writeFileSync(jsonPath, `${JSON.stringify(ordered, null, 2)}\n`);
  writeFileSync(tsPath, renderContracts(abis, ordered));
  console.log(`Wrote ${path.relative(process.cwd(), tsPath)}`);
}
