import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import hre from "hardhat";

const names = ["NixToken", "IntentRegistry", "NixPool", "NixLaunch", "NixLaunchpad", "NixPair", "LaunchToken"] as const;

async function main() {
  const configDir = path.join(process.cwd(), "frontend", "config");
  const jsonPath = path.join(configDir, "deployments.json");
  const deployments = existsSync(jsonPath) ? JSON.parse(readFileSync(jsonPath, "utf8")) : {};
  const abis: Record<string, unknown> = {};
  for (const name of names) {
    abis[name] = (await hre.artifacts.readArtifact(name)).abi;
  }
  mkdirSync(configDir, { recursive: true });
  const body = `// Generated by scripts/deploy.ts. Do not edit by hand.

export const abis = ${JSON.stringify(abis, null, 2)} as const;

export const deployments = ${JSON.stringify(deployments, null, 2)} as const;
`;
  writeFileSync(path.join(configDir, "contracts.ts"), body);
  console.log(`Wrote frontend ABIs for ${names.join(", ")}.`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
